"""Audiofile

Revision ID: e29369c3436b
Revises:
Create Date: 2025-03-29 16:17:05.748280

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str | None = "e29369c3436b"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_files",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "filename", name=op.f("audio_files_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audio_files")
    # ### end Alembic commands ###
